/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiMessagesIndexRouteImport } from './routes/api/messages/index'
import { Route as ApiMessagesIdRouteImport } from './routes/api/messages/$id'
import { Route as ApiMessagesClearRouteImport } from './routes/api/messages/clear'
import { Route as ApiMessagesTestRouteImport } from './routes/api/messages/test'
import { Route as ApiMessagesIdRawRouteImport } from './routes/api/messages/$id/raw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesIndexRoute = ApiMessagesIndexRouteImport.update({
  id: '/api/messages/',
  path: '/api/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesIdRoute = ApiMessagesIdRouteImport.update({
  id: '/api/messages/$id',
  path: '/api/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesClearRoute = ApiMessagesClearRouteImport.update({
  id: '/api/messages/clear',
  path: '/api/messages/clear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesTestRoute = ApiMessagesTestRouteImport.update({
  id: '/api/messages/test',
  path: '/api/messages/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesIdRawRoute = ApiMessagesIdRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ApiMessagesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/messages/$id': typeof ApiMessagesIdRouteWithChildren
  '/api/messages/clear': typeof ApiMessagesClearRoute
  '/api/messages/test': typeof ApiMessagesTestRoute
  '/api/messages/': typeof ApiMessagesIndexRoute
  '/api/messages/$id/raw': typeof ApiMessagesIdRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/messages/$id': typeof ApiMessagesIdRouteWithChildren
  '/api/messages/clear': typeof ApiMessagesClearRoute
  '/api/messages/test': typeof ApiMessagesTestRoute
  '/api/messages': typeof ApiMessagesIndexRoute
  '/api/messages/$id/raw': typeof ApiMessagesIdRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/messages/$id': typeof ApiMessagesIdRouteWithChildren
  '/api/messages/clear': typeof ApiMessagesClearRoute
  '/api/messages/test': typeof ApiMessagesTestRoute
  '/api/messages/': typeof ApiMessagesIndexRoute
  '/api/messages/$id/raw': typeof ApiMessagesIdRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/status'
    | '/api/messages/$id'
    | '/api/messages/clear'
    | '/api/messages/test'
    | '/api/messages/'
    | '/api/messages/$id/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/status'
    | '/api/messages/$id'
    | '/api/messages/clear'
    | '/api/messages/test'
    | '/api/messages'
    | '/api/messages/$id/raw'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/status'
    | '/api/messages/$id'
    | '/api/messages/clear'
    | '/api/messages/test'
    | '/api/messages/'
    | '/api/messages/$id/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiMessagesIdRoute: typeof ApiMessagesIdRouteWithChildren
  ApiMessagesClearRoute: typeof ApiMessagesClearRoute
  ApiMessagesTestRoute: typeof ApiMessagesTestRoute
  ApiMessagesIndexRoute: typeof ApiMessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/': {
      id: '/api/messages/'
      path: '/api/messages'
      fullPath: '/api/messages/'
      preLoaderRoute: typeof ApiMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$id': {
      id: '/api/messages/$id'
      path: '/api/messages/$id'
      fullPath: '/api/messages/$id'
      preLoaderRoute: typeof ApiMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/clear': {
      id: '/api/messages/clear'
      path: '/api/messages/clear'
      fullPath: '/api/messages/clear'
      preLoaderRoute: typeof ApiMessagesClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/test': {
      id: '/api/messages/test'
      path: '/api/messages/test'
      fullPath: '/api/messages/test'
      preLoaderRoute: typeof ApiMessagesTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$id/raw': {
      id: '/api/messages/$id/raw'
      path: '/raw'
      fullPath: '/api/messages/$id/raw'
      preLoaderRoute: typeof ApiMessagesIdRawRouteImport
      parentRoute: typeof ApiMessagesIdRoute
    }
  }
}

interface ApiMessagesIdRouteChildren {
  ApiMessagesIdRawRoute: typeof ApiMessagesIdRawRoute
}

const ApiMessagesIdRouteChildren: ApiMessagesIdRouteChildren = {
  ApiMessagesIdRawRoute: ApiMessagesIdRawRoute,
}

const ApiMessagesIdRouteWithChildren = ApiMessagesIdRoute._addFileChildren(
  ApiMessagesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiMessagesIdRoute: ApiMessagesIdRouteWithChildren,
  ApiMessagesClearRoute: ApiMessagesClearRoute,
  ApiMessagesTestRoute: ApiMessagesTestRoute,
  ApiMessagesIndexRoute: ApiMessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
